### ISSUE TITLE
Update mantra docs

### ISSUE THREAD

**Issue by shoetten** [gadicc/meteor-hmr#106]
Hey,
sorry to ask this, but there have been so many changes in the last couple days, that i can't keep up..

Could somebody update the mantra specific docs and/or [this repo](https://github.com/gadicc/mantra-sample-blog-app-hot), for use with the 'newest' setup (e.g. `Meteor 1.3.3`, `ecmascript-hot@2.0.0-beta.4` and `react-hot-loader@3.0.0-beta.2`)?

I really want to get this to work, since developing without HMR is a pain..
Thanks in advance!

**Comment by Vincent-P** [comment]
What is the issue exactly ?

**Comment by gadicc** [comment]
Just bumped all versions to latest in the repo, obv none of these things are out of beta though :D  Re-open if you run into any problems.  https://github.com/gadicc/mantra-sample-blog-app-hot/compare/5ef0398...1e1fb72
