### ISSUE TITLE
Redbox problem

### ISSUE THREAD

**Issue by tomitrescak** [gadicc/meteor-hmr#118]
Hi, I know that this is not probably the best place to ask, but you know the hot stack better than anyone. My problem is that with beta.5. somehow the redox is configured and added by itself. While I do not mind redox, my problem is that it does not produce errors in the console and the errors displayed in the RSOD are not clickable. Any idea how cn I change this behaviour, or just remove the redox as a whole?

**Comment by gadicc** [comment]
Yes, it's the default for RHL's `AppContainer`.  Check https://github.com/gaearon/react-hot-loader/blob/next-docs/docs/TipsAndTricks.md which will be in the final docs when RHL is released.

**Comment by tomitrescak** [comment]
Thanks!! That works ;)
