### ISSUE TITLE
Are you running tests on other packages?

### ISSUE THREAD

**Issue by gsabran** [gadicc/meteor-hmr#49]
I've tried to start meteor on port 8080, and that fails because a test in `less` tries to access port 8081 (https://github.com/less/less.js/blob/master/test/browser/less/urls.less#L2-L3)
That is not happening without this package. So:
- are you using 8081 and it was not used before? If so how can I change that?
- are you running tests that would not get run else? If so how to disable that?

**Comment by gsabran** [comment]
Actually, it might come from the fact that I upgraded Meteor at the same time. Removing the package doesn't solve the issue, but reverting the commit (that includes Meteor upgrade does)

**Comment by gadicc** [comment]
I know there was a lot of work regarding CSS imports in the last Meteor release.. my suspicion is maybe that Meteor was ignoring these lines before but respecting them now, but it still doesn't explain why removing the package didn't help.

The bigger question however is why those less tests are running for you at all?  How did you install the less package?  (Also, doesn't Meteor provide it's own less packages?  I'm less familiar with it.)

The answer your question though, if you run Meteor on port 8080, Meteor will run mongo on port 8081 and we'll use port 8082 for the accelerator.

Those less tests will always fail unless you run the code in less's test environment.

**Comment by gadicc** [comment]
Hey @gsabran I'm pretty sure this is unrelated to meteor-hmr but feel free to re-open if you have any more input.
