### ISSUE TITLE
Mantra

### ISSUE THREAD

**Issue by Vincent-P** [gadicc/meteor-hmr#52]
Hi,

I tried to add the reloader to my mantra app without success.
Can you add some explanations ?

Thanks

**Comment by clayne11** [comment]
Have you followed the installation instructions are found on the home page?

**Comment by Vincent-P** [comment]
I have a `TypeError: _context is undefined` when importing the patch.

**Comment by clayne11** [comment]
So you're trying the `refactor.5` release? Please give as much as information as possible, including a stack trace and which release of `gadicc:ecmascript-hot` that you're using.

If you can post your repo as well that would be very helpful.

**Comment by Vincent-P** [comment]
I am using this : 
```
gadicc:babel-compiler-hot@6.6.1_1
gadicc:ecmascript-hot@1.3.1_1
gadicc:hot@0.0.16
gadicc:json5@0.5.0-0
gadicc:modules-runtime-hot@0.6.2_2
```

I am just trying it on mantra-sample-blog.

**Comment by clayne11** [comment]
If you're just testing it out you're probably best waiting a few days until the next release comes out. It's going to be significantly different. You're probably better off even using it right now - it's much, much faster and we want to find all the bugs in the new version not this old one.

See https://github.com/gadicc/meteor-react-hotloader/issues/51

**Comment by gadicc** [comment]
Sorry, that's my bad.  The situation is word-for-word what @clayne11 said.  I've added the following to the top of the README:

> **NB: This README refers to the upcoming release.  Although it's experimental, you're encouraged to try it out, since that's the direction we're going in.  More details in [#51](https://github.com/gadicc/meteor-react-hotloader/issues/51).  Otherwise, you can find the old README [here](https://github.com/gadicc/meteor-react-hotloader/blob/1352a7a0335ebeab3684ca8fdd096c2b5749da05/README.md).**

**Comment by Vincent-P** [comment]
Ok I'll try refactor release.
