### ISSUE TITLE
[Windows] hot-build meteor packages path

### ISSUE THREAD

**Issue by Vincent-P** [gadicc/meteor-hmr#58]
The next issue ( after meteor tool path #56 ) is meteor package path in hot-build.
```js
// meteor-hmr/hot-build/hot-server.js:71

  var METEOR_HOME = path.join(process.env.HOME, '.meteor');
```

**Comment by gadicc** [comment]
oh wow, I didn't see this... you beat me by 2m haha!  nicely done.  have you tested this?  it wasn't clear to me from meteor's code if METEOR_INSTALLATION is actually the user's home dir, or `~/.meteor` - I went with the former, since on non-windows it returns process.env.HOME;

**Comment by Vincent-P** [comment]
Yes METEOR_INSTALLATION works on Windows but I dont know how it works on Linux and OSX.

**Comment by gadicc** [comment]
If your're running from the latest Master, I introduced code earlier to log the name of the file it fails to watch in this case... if it did, can you paste it?  Otherwise I'll have a chance to look at this again tomorrow.

**Comment by gadicc** [comment]
Sorry ignore that, hadn't seen your next message yet.  So can you just confirm what METEOR_INSTALLATION looks like for you?  This has been incredibly helpful saving me from setting up a Windows VM :)

**Comment by Vincent-P** [comment]
Yes of course,
```js
// C:\Users\vince\AppData\Local\.meteor\
process.env.METEOR_INSTALLATION
```

**Comment by gadicc** [comment]
Amazing, thanks!  Windows users everywhere are thanking you :)
