### ISSUE TITLE
RHLv3 and Mantra style apps

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-hmr#60]
Currently react-hot-loader/patch is breaking Mantra. Need to investigate further. For now, you can still use the HMR without react-hot-loader: hot reloading will work but state stored inside components will be lost on updates.

See https://github.com/gadicc/mantra-sample-blog-app-hot.

**Comment by Vincent-P** [comment]
So this part of the README needs to be updated : 

> 1. Works great with
[mantra-sample-blog-app](https://github.com/mantrajs/mantra-sample-blog-app)
(but you need to remove `babel-root-slash-import`, which might break some
of your testing, tracking in
[#82](https://github.com/mantrajs/mantra-sample-blog-app/issues/82)).

**Comment by gadicc** [comment]
Ooh wow, yes, on that!

**Comment by Vincent-P** [comment]
I don't know how it is supposed to work with currently only the main layout hot reloads.

**Comment by gadicc** [comment]
Oops, you're right... PostList, Post and NewPost aren't reloaded, I need to add in some logic for this.  Sorry, I rushed to try get something up before I went away, so I missed this, and don't have any more time now :(  I'm back on Tuesday if you or anyone else doesn't manage to figure something out by then, I'd still like to try find a better pattern.

**Comment by gadicc** [comment]
I'm back and have updated the repo there, everything works now, including component-level state (thanks for the latest RHL beta).

**Comment by gadicc** [comment]
Thanks again for all the help last week!  I'm closing this, because I'm pretty sure it's solved.  But please re-open if any issues or comments.

**Comment by tomitrescak** [comment]
Is the mantra example repo maintained? Thanks for all the amazing work!

**Comment by gadicc** [comment]
thanks @tomitrescak!  which one?  the original or the -hot one?  I think the original is maintained but I think still on an 1.3-rc iirc.  the -hot one is from a few days ago, so it's up to date now, not sure what the future will look like :D  but the main idea there is just to show the pattern / changeset from original mantra.
