### ISSUE TITLE
Mantra / Flow Router issue

### ISSUE THREAD

**Issue by Vincent-P** [gadicc/meteor-hmr#70]
## Description of Problem

There is an issue with flow routers routes that has params : `TypeError: _ref3 is undefined`

For example this one has a **postId** param
```js
FlowRouter.route('/post/:postId', {
    name: 'posts.single',
    action({postId}) {
      const Post = require('./containers/post').default;
      mount(MainLayoutCtx, {
        content: () => (<Post postId={postId}/>)
      });
    }
  });
```
![issue_hot](https://cloud.githubusercontent.com/assets/10779205/15083419/55e798d4-13cd-11e6-8481-c0bc0644d547.png)

## Fixing it

The problem is here : 

```js
if (module.hot) {
  module.hot.accept([
    './components/main_layout',
    './containers/postlist',
    './containers/post',
    './containers/newpost',
  ], function () {
    // If any of the above files (or their dependencies) are updated, all we
    // really need to do is re-run the current route's action() method, which
    // will require() the updated modules and re-mount MainLayoutCtx
    // (which itself require()'s the updated MainLayout at render time).
    localFlowRouter._current.route._action();
  });
}
```

We call the current route action without parameters so we just have to call it with these :

```js
localFlowRouter._current.route._action(localFlowRouter._current.params);
```

## Environment

* Meteor version: 1.3.2.4
* ecmascript-hot version: refactor 12
* Operating System: Windows 10

**Comment by gadicc** [comment]
Awesome!  Thanks for picking this up and providing the fix.
