### ISSUE TITLE
A simple startup tutorial

### ISSUE THREAD

**Issue by s7dhansh** [gadicc/meteor-hmr#76]
Since the last three and a half hours, I have been skimming through the docs, to not much avail. With @gadicc guidance this is how I got it working.

So far I have done:

1. change `ecmascript` to `gadicc:ecmascript-hot@=1.3.2-refactor.8` in .meteor/packages  (The docs say just `gadicc:ecmascript-hot`)
2. `npm install --save-dev react-hot-loader@^3.0.0-beta.2 redbox-react babel-preset-meteor`
3. Added a .babelrc with the following
    ```
    {
      "presets": ["meteor"],
      "plugins": ["react-hot-loader/babel"]
    }
    ```
4. Restart meteor
5. Add `import 'react-hot-loader/patch';` before as the **first line** of client side code.
6. In your routes.jsx, add `import { AppContainer } from "react-hot-loader";`
7. Change you `MainLayout` in your routes.jsx from something like 
```
import MainLayout from "/imports/ui/layouts/main";
```
to
```
const MainLayout = function(props) {
	const Layout = require("/imports/ui/layouts/main").default;
	return (
		<AppContainer>
			<Layout {...props} />
		</AppContainer>
	);
};
``` 
8. Add hot reload code in the end of the routes.jsx:
```
if (module.hot) {
	module.hot.accept([
		"/imports/ui/layouts/main",
		"/imports/ui/pages/home",
		"/imports/ui/components/footer/footer",
	], function() {
		// If any of the above files (or their dependencies) are updated, all we
		// really need to do is re-run the current route"s action() method, which
		// will require() the updated modules and re-mount MainLayoutCtx
		// (which itself require()"s the updated MainLayout at render time).
		FlowRouter._current.route._action(localFlowRouter._current.params);
	});
}
```
Done!

Now you have to use your pages as requires in the Router action(), and add them to module.hot.accept, for hot reload to work.

P.S. We can also use errorReporter something like this, https://github.com/gadicc/mantra-sample-blog-app-hot/compare/master...gadicc:hot

**Comment by gadicc** [comment]
Hey, this all looks good.

Did you completely stop and restart Meteor after the babelrc changes?  We used to quit for you if you modified these files, but we recently disabled that to see if it fixes another issue.

If you did, if you can put your code in a cloneable repo somewhere I'll take a quick look.

You still need steps 3 & 4 from https://github.com/gadicc/meteor-hmr/blob/master/docs/Upgrading.md#add-the-new-setup, but you should get partial hotloading even without this, and certainly no errors.

**Comment by s7dhansh** [comment]
@gadicc Thank you for a prompt response.

I found it,

in step 1. I should use `gadicc:ecmascript-hot@=1.3.2-refactor.8` and not `gadicc:ecmascript-hot`. I am getting some errors, but they are related to code. I will fix them and revert.

**Comment by gadicc** [comment]
Ah, great stuff... I should have noticed that :D  This confusion will end fairly soon when we publish the final stable release of the new code.

**Comment by s7dhansh** [comment]
So I am getting a lot of code errors - This is an old project with lots of globals defined in files 
```
Config = {}
```
`ecmascript` allowed them, but your ecmascript shows errors. Any simple way to overcome them? Or will I have to convert all of them to consts and exports?

**Comment by s7dhansh** [comment]
Oh, I think it is because of addition "es2015" in my babelrc.

**Comment by s7dhansh** [comment]
Update this as a working tutorial!

**Comment by gadicc** [comment]
Thanks for reporting back, @s7dhansh.  Happy you're up and running.

I'll leave this open until I have a chance to see how I can update https://github.com/gadicc/meteor-hmr/blob/master/docs/React_Hotloading.md to be clearer.
