### ISSUE TITLE
No relevant hot accept

### ISSUE THREAD

**Issue by tomitrescak** [gadicc/meteor-hmr#77]
Hi, I am using the latest "refactor.12".
I have cloned the mantra repo where everything worked perfectly.

Then I added my changes and from this moment on the app keeps complaining:

```
hot.js:77 [gadicc:hot] No (relevant) hot.accept() in /imports/client/modules/core/components/layout_main_view.jsx > /imports/client/utils/router_utils.jsx > /imports/client/configs/context.js > /imports/client/main.js > /app/client/main.js.  Need to reload.
```

I have following code in my routes:

```
if (module.hot) {
    module.hot.accept([
        './components/layout_main_view'
    ], function () {
        // If any of the above files (or their dependencies) are updated, all we
        // really need to do is re-run the current route's action() method, which
        // will require() the updated modules and re-mount MainLayoutCtx
        // (which itself require()'s the updated MainLayout at render time).
        localFlowRouter._current.route._action(localFlowRouter._current.params);
    });
}
```

And the component exists where I specified (it has a jsx suffix though as it is compiled from typescript).

Any idea what may bo the reason for this issue?

**Comment by s7dhansh** [comment]
How are you using it in your router? As an import, or as a require inside the layout context?

**Comment by tomitrescak** [comment]
This is my router file. Sorry it's typescript, but should be pretty clear:

```javascript
import React from 'react';
import {mount} from 'react-mounter';
import { AppContainer } from 'react-hot-loader';

// import MainLayout from './components/main_layout';
// import PostList from './containers/postlist';
// import Post from './containers/post';
// import NewPost from './containers/newpost';

// Optional, but helpful
import Redbox from 'redbox-react';
const consoleErrorReporter = ({error}) => {
  /* eslint no-console: 0 */
  console.error(error);
  return <Redbox error={error} />;
};
consoleErrorReporter.propTypes = {
  error: React.PropTypes.instanceOf(Error).isRequired
};

// So we can call FlowRotuer again later during hot reload
let localFlowRouter: any;

export default function (injectDeps, {FlowRouter}) {
  // MainLayoutCtx = injectDeps(MainLayout);
  localFlowRouter = FlowRouter;

  const MainLayoutCtx = function(props) {
    const MainLayout = require('./components/layout_main_view').default;
    const MainLayoutCtx = injectDeps(MainLayout);
    return (
      <AppContainer errorReporter={consoleErrorReporter}>
        <MainLayoutCtx {...props} />
      </AppContainer>
    );
  };

  FlowRouter.route('/', {
    name: 'posts.list',
    action() {
      const Editor = require('../editor/components/editor_view').default;
      mount(MainLayoutCtx, {
        content: () => (<Editor />)
      });
    }
  });
}

if (module.hot) {
  module.hot.accept([
    './components/layout_main_view',
    '../editor/components/editor_view',
    '../eis/components/eis_list_view'
  ], function () {
    // If any of the above files (or their dependencies) are updated, all we
    // really need to do is re-run the current route's action() method, which
    // will require() the updated modules and re-mount MainLayoutCtx
    // (which itself require()'s the updated MainLayout at render time).
    localFlowRouter._current.route._action(localFlowRouter._current.params);
  });
}
```

**Comment by s7dhansh** [comment]
I started a few hours ago, so I have very less idea about this stuff. But on the first look, things seem ok. May be someone else may help you :)

**Comment by gadicc** [comment]
hey @tomitrescak :)

Can you confirm that your routes are in `/imports/client/utils/router_utils.jsx` ?

If so, you probably need to specify `../modules/core/components/layout_main_view.jsx` instead of `./components/layout_main_view`.

Otherwise are you maybe importing `layout_main_view` from multiple files?

**Comment by tomitrescak** [comment]
@gadicc yes, I am importing that layout file in multiple files :/ How does that interfere with the process?

After commenting out that second import, all was fixed. Thanks a lot!
Maybe this would be great in readme, if it there already I sincerely apologise!

**Comment by gadicc** [comment]
Multiple files are ok as long as there's a hot.accept() somewhere between the changed file and your app entry point.

Let's think about what's happening:
* It's imported by routes and displayed there... so that's fine, if it changes, we re-import, remount, and all is good.
* It's imported also somewhere else.... what should happen there if the file changes now?  Unless something says "oh ok, this changed, and I can do something with that", we have no choice but to reload the whole site.

It's also ok to hot.accept() further down in the import chain though.  You could also have something in `/imports/client/configs/context.js`:

```js
if (module.hot)
  module.hot.accept('../utils/router_utils',
    function() {
      // do something with
      const nextRouterUtils = require('../utils/router_utils');
    }
  );
```

I know these concepts are confusing at first, but after you get used to it, it makes a lot more sense.  I'll try update https://github.com/gadicc/meteor-hmr/blob/master/docs/Troubleshooting.md#no-hotaccept-in-clientnon-hot-updatejs--clientindexjsx to make this a bit clearer.

**Comment by tomitrescak** [comment]
Hmm, I reverted back to my original solution, where I want to keep the the mainlayout import in the router_utils file. But I cannot simply make it work.

I get the same message:

```
[gadicc:hot] No (relevant) hot.accept() in /imports/client/modules/core/components/layout_main_view.jsx > /imports/client/utils/router_utils.jsx > /imports/client/configs/context.js > /imports/client/main.js > /app/client/main.js.  Need to reload.
```

My router.jsx file is in: `/imports/client/modules/core/routes.jsx`

I modified the accept chain to this:

```javascript
if (module.hot) {
  module.hot.accept([
    '../modules/core/components/layout_main_view.jsx',
    '../editor/components/editor_view',
    '../eis/components/eis_list_view'
  ], function () {
    localFlowRouter._current.route._action(localFlowRouter._current.params);
  });
}
```

Where is the root of these paths? Thanks.

**Comment by tomitrescak** [comment]
Hm, your solution with placing the hot section inside the context worked:

```
if (module.hot)
  module.hot.accept('../utils/router_utils',
    function() {
      // do something with
      const nextRouterUtils = require('../utils/router_utils');
    }
  );
```

But why? It is a bit confusing ;/

**Comment by gadicc** [comment]
Wait, you can't just use that code as is :)  It's a starting point :>  Let's think again, ignoring the route part which is working.

1. `layout_main_view.jsx` is updated
1. `router_utils.jsx` imports it.  So now something `route_utils` imports has changed.  Somewhere we have to accept that change (i.e. say, "ok, that changed, and I know how to handle that change without reloading the entire bundle from scratch".  e.g. with the routes, we remount the current route with the new imports).
1. If `router_utils` can't accept the change for `layout_main_view`, we need to keep going down the chain.  If we were to completely reload just `router_utils`, it would use the new `layout_main_view`.  So maybe there's something that imports `router_utils` that can handle the change.
1. In the code above, `nextRouterUtils` is the newly loaded `router_utils` (which has the new `layout_main_view` inside of it).  So we could handle the change here.  If we don't, we keep looking at what imports the next file, up until we reach a file that is not imported by anything else, and then we have to fail and reload the entire page.

I dunno if that makes any more sense...  I agree it's confusing at first.  I'm not sure if https://github.com/gadicc/meteor-hmr/blob/master/docs/Handling_Updates.md helps at all, you can look at the webpack docs linked from there for further info but those are also a bit hard to understand at first.

**Comment by tomitrescak** [comment]
@gadicc  now I understand the process, great explanation. The question is, why does it work then;) the code that you gave me works like a charm:)

**Comment by gadicc** [comment]
Very happy it all made sense; after I re-read what I wrote, I was a bit dubious :)

Mmm, it should get rid of the error, but not update react components currently on the screen unless some other code higher up (in `router_utils`) is doing something to trigger a re-render?  (update some state somewhere or otherwise change a prop below the component being updated).

**Comment by gadicc** [comment]
Oh wait, don't you still have the *other* hot.accept() somewhere?  That's doing the change, and this one is just silently ending / potentially breaking.

The question is, why do you import `layout_main_view` in `router_utils`?  What does `context` do with `router_utils` ?  I guess you have `layout_main_view` added to your main context somewhere... but the context is never updated.  So your context will always point to the original `layout_main_view`, not the updated one.

**Comment by tomitrescak** [comment]
Yes, I did have that second update there, but that second one was not doing anything and was still giving me the same error. Let me play with this a bit more to understand it better. Thanks for all your help and great documentation!

**Comment by alvelig** [comment]
First of all great thanks for the library 

```
[gadicc:hot] Aborting circular dependency, no relevant hot.accept() in /imports/ui/Common/Partials/RightTopSection.jsx > /imports/ui/Users/Clia/Clia.jsx > /imports/ui/Users/UserRoles.jsx.  Need to reload.
hot.js:57 [gadicc:hot] Aborting circular dependency, no relevant hot.accept() in /imports/ui/Common/Partials/RightTopSection.jsx > /imports/ui/Users/Cliw/Cliw.jsx > /imports/ui/Users/UserRoles.jsx.  Need to reload.
hot.js:57 [gadicc:hot] Aborting circular dependency, no relevant hot.accept() in /imports/ui/Common/Partials/RightTopSection.jsx > /imports/ui/Users/Jefe/Jefe.jsx > /imports/ui/Users/UserRoles.jsx.  Need to reload.
hot.js:57 [gadicc:hot] Aborting circular dependency, no relevant hot.accept() in /imports/ui/Common/Partials/RightTopSection.jsx > /imports/ui/Users/OPCO/OPCO.jsx > /imports/ui/Users/UserRoles.jsx.  Need to reload.
```
