### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by tomitrescak** [gadicc/meteor-hmr#82]
Just a question here. If I'll use redux, anything changes for me? Is there any best practice? Thanks!

**Comment by gadicc** [comment]
No required changes, but depending on your setup, you can hotload changes to your reducers :)  e.g. the todomvc example's [store/configureStore.js](https://github.com/reactjs/redux/blob/64a8c66b454163660f9d49bcce92a3230cdbcb2a/examples/todomvc/store/configureStore.js):

```js

import { createStore } from 'redux'
import rootReducer from '../reducers'

export default function configureStore(initialState) {
  const store = createStore(rootReducer, initialState)

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextReducer = require('../reducers').default
      store.replaceReducer(nextReducer)
    })
  }

  return store
}
```

This pattern should be looking more familiar now :)

**Comment by gadicc** [comment]
Happy to answer more questions, just closing this to help my todo list for rc.0 release.
