### ISSUE TITLE
Hotloading (and compiling) of local (in development) node_modules

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-hmr#83]
via `gadicc:node-modules-hot`.

* [X] Watch node_modules for all symlinked directories (i.e. from `npm link`)
* [X] If `src/*` is changed, compile with babel to `lib`
* [X] Hotloading
* [x] Hotloading of `moduleName` instead of current `moduleName/index.js`
* [x] Some tests maybe?
* [x] Add to docs
* [ ] Speed up compilation by using node-babel vs spawn(babel) -- maybe for v2.0.1

This is the last new feature for v2.0.0.

**Comment by rickmed** [comment]
@gadicc where will the release announcement be made? to subscribe :)

**Comment by gadicc** [comment]
@rickmed, thanks for the excitement :)  just from writing here you're subscribed to this issue, you'll get a notice once it's closed.  ecmascript-hot@2.0.0-rc.0 should be out soon after that (I opened #87 if you want to subscribe there too), and I guess a `node-modules-hot@2.0.0-beta.0`.

**Comment by gadicc** [comment]
Haven't had much time to work on / test this lately, but wanted to get it out.  Just published `gadicc:node-modules-hot@2.0.0-beta.0`.  Closing this issue, and will track the upcoming speed improvement in #89.
