### ISSUE TITLE
React Router warnings

### ISSUE THREAD

**Issue by genyded** [gadicc/meteor-hmr#84]
## Description of Problem

Not a huge issue, but using this with react router spits out the warnings below. Everything seems to work OK but it's a bit annoying to have the warnings clutter the console. Not sure if anything can be done about it though.

<details>
<summary>`Console warning`</summary>
```js
browser.js:49 Warning: [react-router] You cannot change <Router routes>; it will be ignored
```
</details>

**Comment by gadicc** [comment]
Yeah, unfortunately not much we can do about it.  See my final comments in https://github.com/gadicc/meteor-hmr/issues/64#issuecomment-217127251.  We can discuss further in that issue.
