### ISSUE TITLE
import _classCallCheck from 'babel-runtime/helpers/classCallCheck';

### ISSUE THREAD

**Issue by ahmadsafar** [gadicc/meteor-hmr#90]
```
W20160519-17:02:03.301(8)? (STDERR) import _classCallCheck from 'babel-runtime/helpers/classCallCheck';
W20160519-17:02:03.301(8)? (STDERR) ^^^^^^
W20160519-17:02:03.301(8)? (STDERR) SyntaxError: Unexpected reserved word
```

i use latest version from atmosphere, but got this error. how to fix that?

**Comment by gadicc** [comment]
Hey, can you be more specific about the version?  Since we have a few experimental and beta releases on Atmosphere too.

But anyways, this is usually a `.babelrc` issue.  Can you try with `meteor` as the *only* preset and see if it resolves your issue?

**Comment by ahmadsafar** [comment]
oh sorry, i use `1.3.2-refactor.12` version.
yeah, my `.babelrc` only have `{ "presets": [ "meteor" ] }`

**Comment by gadicc** [comment]
Oh, great, you're pretty up to date!  You can also try `gadicc:ecmascript-hot@2.0.0-beta.3` which is the continuation from the `refactor` experimental releases.  I don't think it will help with this problem though, but we'll solve it :)

Can you paste the file causing the error or are you able to put your project up on github for me to take a look?

**Comment by ahmadsafar** [comment]
Problem solved. just rebuild `npm` package then the problem is gone!
thanks for your attention and great job. Hope to see stable version of this :D

**Comment by gadicc** [comment]
I wouldn't have guessed that... thanks for taking the time to let us know!  Yeah, we're very close to stable now!  Exciting times :>
