### ISSUE TITLE
Current Package version?

### ISSUE THREAD

**Issue by rickmed** [gadicc/meteor-hmr#93]
I've tried  1.3.0_5 and 1.3.0_4 and I get on both unexpected import reserved word.

meteor 1.3.2.4

Switching to default ecmascript package works

**Comment by clayne11** [comment]
The current version is `2.0.0-beta.3`.

It will be released as a new "stable" release over the next few days, but it's already very stable.

**Comment by rickmed** [comment]
@clayne11 I assumed that one needs meteor 1.3.3.?

**Comment by clayne11** [comment]
Nope. Meteor `1.3.3` only released the first beta yesterday. The `gadicc:ecmascript-hot` rewrite has been in progress for about a month now and is ready to go. I have been using it since day one in my production app.

**Comment by rickmed** [comment]
@clayne11 https://github.com/gadicc/meteor-hmr/blob/master/docs/Upgrading.md 
Now I'm confused what setup should I use

**Comment by clayne11** [comment]
Are you upgrading from `1.3.0_5` or just installing it for the first time? If you're just trying to set it up for the first time don't follow upgrading instructions.

Look at these docs: https://github.com/gadicc/meteor-hmr

**Comment by rickmed** [comment]
upgrading...thanks! @clayne11

**Comment by gadicc** [comment]
Thanks, guys!  Yeah, 1.3.3 is taking a bit longer than I thought, but the `beta.0` does indeed have the promised `.babelrc` support.  Let's track in #97 and #51 and hopefully we'll be stable again soon with up-to-date docs.

The `import - unexpected reserved word` error is something else though, there have been some other issues about that... usually related to the included (or excluded) plugins/presets in `.babelrc` and their order.

Watch the abovementioned issues for more!
