### ISSUE TITLE
Meteor 1.3.3 beta0 compatibility

### ISSUE THREAD

**Issue by priezz** [gadicc/meteor-hmr#97]
## Description of Problem

Hello, Gadi!

Things seem to be broken with the new Meteor beta:
```
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While loading plugin `compile-ecmascript-hot` from package
   `gadicc:ecmascript-hot`:
   error: Can't load npm module 'ws' from
   packages/gadicc_hot-build.js. Check your Npm.depends().
   packages/gadicc_hot-build/accelerator.js:49:1: undefined is
   not a function
   at connect
   (packages/gadicc_hot-build/accelerator.js:49:1)
   at Package
   (packages/gadicc_hot-build/accelerator.js:99:1)
   at packages/gadicc_hot-build/accelerator.js:111:1
   at packages/gadicc_hot-build/accelerator.js:111:1
```

## Environment

* Meteor version: 1.3.3-beta.0
* ecmascript-hot version: gadicc:ecmascript-hot@2.0.0-beta.3
* Operating System: OS X 10.11.5

**Comment by gadicc** [comment]
Watch this space :)  Also cross-posting from [here](https://github.com/gadicc/meteor-hmr/issues/51#issuecomment-220947535):

> Just a heads up, I was planning on releasing a stable this week if nothing came else up, but now with Meteor 1.3.3 beta0 out, I'm going to target that instead, with the aim to release our stable in tandem with the 1.3.3 stable.

> Reason being, I'd prefer to release just one stable, that won't require many more changes. 1.3.3 both has some big under-the-hood changes but also includes its own babelrc supports which massively reduces the strain on this project :)

**Comment by menelike** [comment]
Got METEOR@1.3.3-beta.2 running smooth from current master https://github.com/gadicc/meteor-hmr/commit/c2db1509751f5e355eb88c446a6f47c84408e6e4

**Comment by gadicc** [comment]
Thanks, @menelike, very helpful having others confirm this before publishing.  Everyone else, you can try out `gadicc:ecmascript-hot@2.0.0-beta.4`... as per the updated README and Updating docs, you should remove `meteor` from your `.babelrc` presets and `npm rm --save-dev babel-preset-meteor`.

**Comment by menelike** [comment]
@gadicc 

fantastic job! From our devs experience `METEOR@1.3.3-beta.2` in combination with `gadicc:ecmascript-hot@2.0.0-beta.4` should be considered as the first "productive" release of Meteor.
This is the first time we can use babel, have fast server rebuilds and ever faster (thx to this lib) react rebuilds.

Honestly, thank you very much for your great work.

**Comment by gadicc** [comment]
Thanks @menelike for the great feedback!  Helps keep me motivated especially considering how work on meteor-hmr has delayed my other projects this year :P
