### ISSUE TITLE
Meteor 1.3.3 will not support .babelrc Meteor packages

### ISSUE THREAD

**Issue by clayne11** [gadicc/meteor-hmr#98]
I just found out that Meteor 1.3.3 will not support `.babelrc` in Meteor packages, only in application level code.

https://forums.meteor.com/t/please-help-test-the-latest-1-3-3-beta-release/23837/16

This is going to be a big problem for me and I'm sure some others as well. I think we should keep our own version of `babelrc` support in `gadicc:ecmascript-hot` until MDG rectifies this serious oversight.

What are your thoughts?

**Comment by clayne11** [comment]
@benjamn actually clarified that this won't be the case and there was a miscommunication.

**Comment by gadicc** [comment]
Hey thanks for clarifying, I'm really behind on the forums and wasn't following that thread.  Looks like somewhere I should be present :)  Thanks!

**Comment by gadicc** [comment]
What's actually quite cool about Meteor 1.3.3 is that (I think) you get to have separate .babelrc's per package.
