### ISSUE TITLE
TypeError: Invalid value used as weak map key(…)

### ISSUE THREAD

**Issue by tomitrescak** [gadicc/meteor-hmr#99]
All my hot reloads are failing on this error (am using beta.3):

```
hot.js:121 TypeError: Invalid value used as weak map key(…)

logAndFail	@	hot.js:121
canAccept	@	hot.js:211
requirersUntil	@	hot.js:105
requirersUntil	@	hot.js:110
requirersUntil	@	hot.js:110
requirersUntil	@	hot.js:110
requirersUntil	@	hot.js:110
requirersUntil	@	hot.js:110
requirersUntil	@	hot.js:110
hotWalker	@	hot.js:162
walkFileTree	@	modules-runtime.js?hash=5e943de…&hot=1:477
walkFileTree	@	modules-runtime.js?hash=5e943de…&hot=1:481
walkFileTree	@	modules-runtime.js?hash=5e943de…&hot=1:481
walkFileTree	@	modules-runtime.js?hash=5e943de…&hot=1:481
walkFileTree	@	modules-runtime.js?hash=5e943de…&hot=1:481
walkFileTree	@	modules-runtime.js?hash=5e943de…&hot=1:481
meteorInstallHot	@	hot.js:143
(anonymous function)	@	hot.js?hash=fd252b1…:1
```

**Comment by tomitrescak** [comment]
Hot reload actually performs, but immediatelly afterwards I get this error and full page reload happens.

**Comment by tomitrescak** [comment]
Hmmm .. interesting, I nailed it to one line of code that was cousing this, but I have no idea why. If I remove the following line, all seems to work well (false positive on regexp maybe?)

```
<Button text="Save" onClick={() => save(mark._id, count(mark.result), mark.student)} />
```

**Comment by tomitrescak** [comment]
It had to do with the way I constructed my Button component when I was conditionally selecting the element to render. If anyone encounters the same error, I can explain.

**Comment by gadicc** [comment]
Thanks @tomitrescak, I love waking up to already closed issues ^_^.  Glad you worked this out.

**Comment by tomitrescak** [comment]
I have to reopen this :/

sometimes I generate jsx elements via function. When I do that, the weak map error appears ;(

for Example:

```
function CourseMenuItems() {
 return [
   <div></div>,
  <div></div>,
 ]
}

<List inverted={true} link={true}>{ CourseMenuItems() }</List>
```

**Comment by gadicc** [comment]
That all looks good to me.

Assuming this is only happening on hot reloads and not the initial load, right?  What about without `react-hot-loader/patch`?

Those line numbers point to a problem in your `hot.accept(callback)`, but it could just be part of the re-rendering process.

**Comment by tomitrescak** [comment]
The problem seems to be with React itself and was reported on other websites such as here https://github.com/facebook/react-devtools/issues/198

what seems to fix the issue is to replace all ternary operators with &&.

```javascript
x ? y : null // no, no, no!
x && y // yes!
```
